//
// Created by Siwei Wang on 2026/10/2.
//

#ifndef ROBOMASTER27ECTRAINING2ND_REMOTECONTROL_CALLBACK_H
#define ROBOMASTER27ECTRAINING2ND_REMOTECONTROL_CALLBACK_H

void remote_shadow_init();
#endif //ROBOMASTER27ECTRAINING2ND_REMOTECONTROL_CALLBACK_H
